# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI for releases

on:
  create:
    tags:
      - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - platformVersion: "2023.1"
            pluginSinceBuild: "222.3345.18"
            pluginUntilBuild: "231.*"
            versionSuffix: ""
          - platformVersion: "2024.1"
            pluginSinceBuild: "241"
            pluginUntilBuild: "241.*"
            versionSuffix: "-2024.1"
          - platformVersion: "2024.3"
            pluginSinceBuild: "243"
            pluginUntilBuild: "243.*"
            versionSuffix: "-2024.3"

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: |
          ./gradlew check buildPlugin \
            -PplatformVersion=${{ matrix.platformVersion }} \
            -PpluginSinceBuild=${{ matrix.pluginSinceBuild }} \
            -PpluginUntilBuild=${{ matrix.pluginUntilBuild }} \
            -PpluginVersion=${GITHUB_REF_NAME}${{ matrix.versionSuffix }}
      - name: Archive distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: "antlr-intellij${{ matrix.versionSuffix }}"
          path: build/distributions/*.zip
